name: Main

on:
  push:
    branches: [ master ]

permissions:
  packages: write

env:
  REACT_APP_AUTHORITY: https://accounts.donation.pp.ua/realms/charity
  REACT_APP_REDIRECT_URL: https://donation.pp.ua/
  REACT_APP_BASE_URL: https://api.donation.pp.ua

jobs:
  build-archive:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: charity-ui
          image-tag: latest
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: donation.pp.ua
      - name: Pull image
        run: ssh ubuntu@donation.pp.ua docker compose pull
      - name: Start image
        run: ssh ubuntu@donation.pp.ua docker compose up -d